/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/topbar/AppMenu/index.vue')['default']
    AuthSwiper: typeof import('./src/components/AuthSwiper/AuthSwiper.vue')['default']
    BAccordion: typeof import('bootstrap-vue-next')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next')['BAccordionItem']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next')['BCardFooter']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BlogNavbar: typeof import('./src/components/navbar/BlogNavbar.vue')['default']
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    BProgressBar: typeof import('bootstrap-vue-next')['BProgressBar']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    CartItem: typeof import('./src/components/widgets/CartItem.vue')['default']
    CartOffcanvas: typeof import('./src/components/topbar/CartOffcanvas.vue')['default']
    CustomGLightbox: typeof import('./src/components/CustomGLightbox.vue')['default']
    CustomStickyElement: typeof import('./src/components/CustomStickyElement.vue')['default']
    DemosMenuDropdown: typeof import('./src/components/topbar/AppMenu/DemosMenuDropdown.vue')['default']
    Footer9: typeof import('./src/components/footer/Footer9.vue')['default']
    HelpNavbar: typeof import('./src/components/HelpNavbar.vue')['default']
    Hero: typeof import('./src/components/home/Hero.vue')['default']
    ITyped: typeof import('./src/components/ITyped.vue')['default']
    Jarallax: typeof import('./src/components/Jarallax.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    LogoBox: typeof import('./src/components/topbar/LogoBox.vue')['default']
    MegaMenuDropdown: typeof import('./src/components/topbar/AppMenu/MegaMenuDropdown.vue')['default']
    MenuItem: typeof import('./src/components/topbar/AppMenu/MenuItem.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/topbar/AppMenu/MenuItemWithChildren.vue')['default']
    MobileNavbarToggler: typeof import('./src/components/topbar/MobileNavbarToggler.vue')['default']
    ModalConfirm: typeof import('./src/components/ModalConfirm.vue')['default']
    PagesMenuDropdown: typeof import('./src/components/topbar/AppMenu/PagesMenuDropdown.vue')['default']
    Parallax: typeof import('./src/components/Parallax.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    PasswordStrengthMeter: typeof import('./src/components/PasswordStrengthMeter.vue')['default']
    PortfolioMenuDropdown: typeof import('./src/components/topbar/AppMenu/PortfolioMenuDropdown.vue')['default']
    ResourcesMenuDropdown: typeof import('./src/components/topbar/AppMenu/ResourcesMenuDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopNavbar: typeof import('./src/components/navbar/ShopNavbar.vue')['default']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader.vue')['default']
    StickyHeader: typeof import('./src/components/topbar/StickyHeader.vue')['default']
    ThemeToggleDropdown: typeof import('./src/components/topbar/ThemeToggleDropdown.vue')['default']
    TopNavigationBar2: typeof import('./src/components/TopNavigationBar2.vue')['default']
    TopNavigationBar3: typeof import('./src/components/TopNavigationBar3.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
